$(document).ready(function(){$("body").tooltip({selector:'[data-toggle=tooltip]'});$('.main-introtext').readMoreFade({buttonClass:"intro-text-more"});$('.intro-text-vec').click(function(){})
var docHeight=$(window).height();var footerHeight=$('#footer').height();var footerTop=$('#footer').position().top+footerHeight;if(footerTop<docHeight){$('#footer').css('margin-top',(docHeight-footerTop-15)+'px');}
$('#moreCat').click(function(){n=0;var listItems=$("#secnav li");listItems.each(function(idx,li){var itm=$(li);if(n==9){itm.hide();}
if(n>9){itm.show();}
n++;});})
$('#lessCat').click(function(){n=0;var listItems=$("#secnav li");listItems.each(function(idx,li){var itm=$(li);if(n==9){itm.show();}
if(n>9){itm.hide();}
n++;});})});$(function(){$(".intro-text-vec").click(function(){$(".readMoreFade").click();$(".intro-text-vec").hide();});})
$('#searchOddelekDropdown li a').on('click',function(){$('#searchdropdown').text($(this).html());if($(this).attr('id').replace("odd_","")!="0"){$("#h_search_select").val($(this).attr('id').replace("odd_",""));}else{$("#h_search_select").val("");}});$(function(){$('#nav-top-cart').popover({trigger:"manual",html:true,animation:false,container:"#dropdownWrap",content:function(){return $('#basket-dropdown-wr').html();}}).on("mouseenter",function(){var _this=this;$(this).popover("show");$('.basket-dropdown-pover').mouseleave(function(){$('#nav-top-cart').popover("hide");});}).on("mouseleave",function(){var _this=this;setTimeout(function(){if(!$(".popover:hover").length){$('#nav-top-cart').popover("hide");}},300);})
$('#pomocinkontakt').popover({trigger:"manual",html:true,animation:false,placement:"bottom",container:"#dropdownWrap",content:function(){return $('#pomoc-dropdown-wr').html();}}).on("mouseenter",function(){var _this=this;$(this).popover("show");$('.pomoc-dropdown-pover').mouseleave(function(){$('#pomocinkontakt').popover("hide");});}).on("mouseleave",function(){var _this=this;setTimeout(function(){if(!$(".popover:hover").length){$('#pomocinkontakt').popover("hide");}},300);})
$('#pomocinkontakt').popover({trigger:"hover",html:true,animation:false,placement:"bottom"});$('#profildropdown').popover({trigger:"manual",html:true,animation:false,placement:"bottom",container:"#dropdownWrap",content:function(){return $('#profil-dropdown-wr').html();}}).on("mouseenter",function(){var _this=this;$(this).popover("show");$('.profil-dropdown').mouseleave(function(){$('#profildropdown').popover("hide");});}).on("mouseleave",function(){var _this=this;setTimeout(function(){if(!$(".popover:hover").length){$('#profildropdown').popover("hide");}},300);})
$('#profildropdown').popover({trigger:"hover",html:true,animation:false,placement:"bottom"});})
$('#pomocinkontakt').click(function(){window.location.href='/postaviVprasanje.asp';});$(function(){pos=1;dif=40;$(".dropdown-submenu").each(function(item,element){if(pos>1){$(".dropdown-submenu div.dropdown-menu").eq(pos-1).css('top',dif*(pos-1)*(-1));}
pos++;})})
$(document).ready(function(){loadMenuContent();});$('.nav-top2-dropdown').hover(function(){$('#mainnavig0').show();});$('#mainnavig0').on("mouseleave",function(){setTimeout(function(){if($('.nav-top2-dropdown:hover').length!=1){$('#mainnavig0').fadeOut("fast");}},800);});$('.nav-top2-dropdown').on("mouseleave",function(){setTimeout(function(){if($('#mainnavig0:hover').length!=1){$('#mainnavig0').fadeOut("fast");}},800);});function loadMenuContent(){$("#mainnavig0").html("Nalagam... <img src=\"https://www.enaa.com//images/loader1.gif\"/>");$.ajax({type:"GET",url:"/include/izbiraOddelkaStaticAX.asp",data:"",success:function(html){$("#mainnavig0").html(html);$(".dropdown-submenu").each(function(item,element){if(pos>1){$(".dropdown-submenu div.dropdown-menu").eq(pos-1).css('top',dif*(pos-1)*(-1));}
pos++;})}});}
$('.multi-item-carousel').carousel({interval:false});$('.multi-item-carousel .item').each(function(){var next=$(this).next();if(!next.length){next=$(this).siblings(':first');}
next.children(':first-child').clone().appendTo($(this));if(next.next().length>0){next.next().children(':first-child').clone().appendTo($(this));}else{$(this).siblings(':first').children(':first-child').clone().appendTo($(this));}});$(document).ready(function(){$('#myCarousel').carousel({interval:false});$('.small-thumbnail img').click(function(){$('#DataDisplay').attr("src",$(this).attr("data-display"));});});